// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQYobcEx3Zkp_A4BeADeYj-TuSHA-YfE4',
    appId: '1:188459624872:web:46291b478fb9ac518cd59d',
    messagingSenderId: '188459624872',
    projectId: 'bloc-2ce03',
    authDomain: 'bloc-2ce03.firebaseapp.com',
    storageBucket: 'bloc-2ce03.firebasestorage.app',
    measurementId: 'G-484QQY1W68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7txnuecF81-HH_6h0jgJrAQb6BQ8_nC0',
    appId: '1:188459624872:android:4104263618b927ec8cd59d',
    messagingSenderId: '188459624872',
    projectId: 'bloc-2ce03',
    storageBucket: 'bloc-2ce03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAshq0ZIqGusPdTYRBsBxyjIMaOxLieU8M',
    appId: '1:188459624872:ios:6d8ec2be080a66f68cd59d',
    messagingSenderId: '188459624872',
    projectId: 'bloc-2ce03',
    storageBucket: 'bloc-2ce03.firebasestorage.app',
    iosBundleId: 'com.example.blocStateManagemnet',
  );
}
